### ISSUE TITLE
urls.py uses deprecated syntax for Django 1.10

### ISSUE THREAD

**Issue by Routhinator** [wtayyeb/static-foundation#2]
Current syntax:

```
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

# Test patern, renders Zurb Foundation default page using base template
urlpatterns = patterns('',
    url(regex=r'^$',
        view=TemplateView.as_view(template_name="foundation/index.html"),
        name="foundation_index"),

    url(regex=r'^scss/$',
        view=TemplateView.as_view(template_name="foundation/scss/index.html"),
        name="foundation_scss_index"),

    url(regex=r'^icons/$',
        view=TemplateView.as_view(template_name="foundation/icons.html"),
        name="foundation_icons"),
)
```

New Syntax:

```
from django.conf.urls import url
from django.views.generic import TemplateView

# Test patern, renders Zurb Foundation default page using base template
urlpatterns = [
    url(regex=r'^$',
        view=TemplateView.as_view(template_name="foundation/index.html"),
        name="foundation_index"),

    url(regex=r'^scss/$',
        view=TemplateView.as_view(template_name="foundation/scss/index.html"),
        name="foundation_scss_index"),

    url(regex=r'^icons/$',
        view=TemplateView.as_view(template_name="foundation/icons.html"),
        name="foundation_icons"),
]
```

In it's current state this package's URLs cannot be imported in Django 1.10:

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f08841229d8>
Traceback (most recent call last):
  File "/home/routh/.virtualenvs/the_den/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/routh/.virtualenvs/the_den/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/home/routh/.virtualenvs/the_den/lib/python3.4/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/routh/.virtualenvs/the_den/lib/python3.4/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/routh/.virtualenvs/the_den/lib/python3.4/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/routh/.virtualenvs/the_den/lib/python3.4/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/routh/.virtualenvs/the_den/lib/python3.4/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/routh/.virtualenvs/the_den/lib/python3.4/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/routh/.virtualenvs/the_den/lib/python3.4/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/routh/.virtualenvs/the_den/lib/python3.4/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/routh/.virtualenvs/the_den/lib/python3.4/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/routh/.virtualenvs/the_den/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/routh/Development/Projects/the_den_django/config/urls.py", line 22, in <module>
    from foundation import urls as foundation_urls
  File "/home/routh/.virtualenvs/the_den/lib/python3.4/site-packages/foundation/urls.py", line 1, in <module>
    from django.conf.urls import patterns, url
ImportError: cannot import name 'patterns'
```

**Comment by wtayyeb** [comment]
could you create a fix and make a pull request?

**Comment by wtayyeb** [comment]
no urls anymore! it is just a static package.
